### ISSUE TITLE
[Feature] ChatBox always slow to get new models. Custom model setting?

### ISSUE THREAD

**Issue by perholmes** [Bin-Huang/chatbox#1220]
Hi,

ChatBox is always slow to get new models. I've wanted to use Claude 3 for some time now, and it has actually forced me to start looking for a ChatBox alternative, because it seems like it's weeks or months before ChatBox gets an update that allows using a new model, which is usually just a single text field in the query.

Is there any chance you could make a custom model input if the model you want isn't on the list? Why make ChatBox depend on constant updates to set a trivial JSON field in the query? It means that ChatBox will always be 1-2 months behind the latest models. Always.

Yes, you can use the Claude sandbox. But that's true for all of them. The only reason ChatBox is worth using is because those API tester pages are terrible. So I feel like ChatBox is somewhat failing at its core use case.

**Comment by garlandcrow** [comment]
Yea I'm kinda in the same boat. I love Chatbox and don't really want an alternative but want to try claude3 so have no other choice. Even if you had a pay tier where the updates were fast and I had to pay to get them before it's released to the free version I'd rather do that and support. I don't think there's anything new that needs to be done to support new modes in general when something like Claude or OpenAI has a new model, so this should be easily done and easy way to monetize.

**Comment by Bin-Huang** [comment]
This indeed reminds me. I used to maintain frequent updates (about once a week), but later some users complained that the updates were too frequent, so I changed to updating every three weeks or monthly. This version has accumulated many changes, and I was very willing to release it ahead of schedule, but due to this update frequency restriction, I had to delay the release. Thank you for your all views, they helped me understand what I should really focus on.

**Comment by Bin-Huang** [comment]
By the way, I think that providing a way to customize the model name does not effectively solve all the problems. Because this time the Claude model has updated the API interface based on messages, it still requires modifications to the underlying code to implement.
