### ISSUE TITLE
[Other] How do I use Cloude API?

### ISSUE THREAD

**Issue by PlayerYK** [Bin-Huang/chatbox#1221]
I have been encountering an error message which says:

> An error has occurred with Claude, which is usually caused by incorrect settings or account issues. Please check your AI settings and account status, or [click here to view the FAQ document](https://chatboxai.app/redirect_app/faqs/en).
>
>API Error: Status Code 401, {"type":"error","error":{"type":"authentication_error","message":"x-api-key header is required"}}

I have attached a screenshot of my settings screen. Can you please take a look and let me know if there is anything else that I need to do? Here is the screenshot: 
<img width="600" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/672711/7d31bd97-4abe-49b2-a19c-404c5dfd6bc7">

**Comment by Bin-Huang** [comment]
I think this may be because many models in the Claude 1 series are no longer officially maintained, as I can no longer find related introductions in the documentation https://docs.anthropic.com/claude/docs/models-overview . Maybe you could try switching to the latest model versions, such as the Claude 3 or Claude 2 series.
