### ISSUE TITLE
[Other] Remove "Current model" injection from system prompt??

### ISSUE THREAD

**Issue by nullstreak** [Bin-Huang/chatbox#1227]
The following line injected in the beginning of every system prompt set by user:

```
Current model: name_of_the_model_used

*Rest of the system prompt goes here.*
```

This prefix dilutes context and confuses LLM, creating unexpected/undesired behavior. 

For example:

![image](https://github.com/Bin-Huang/chatbox/assets/139914347/f43c515a-1a1e-46a0-954e-4e72247f162b)

**Comment by Bin-Huang** [comment]
I included that prompt previously since many people were trying to ask GPT-4 about its version and kept getting 'gpt-3' as an answer, leading them to believe this was a bug in Chatbox. After repeatedly clarifying that this was due to the lack of a prompt, I added that line to reduce the need for further explanations. Thank you for your advice; I will remove that line from the prompt.

**Comment by Bin-Huang** [comment]
I have carefully reviewed the code, and this prompt line only affects the two model providers, Azure and OpenAI, without impacting others. I believe this prompt line is still necessary. It seems that you are using OpenAI's provider interface to access other services, which I think is a special case. Perhaps, instead of removing the prompt line, I should consider adding support for this particular service.
