### ISSUE TITLE
[BUG] When using the OpenAI API provider, "Current model: XXX" will be added at the begining of the system prompt.

### ISSUE THREAD

**Issue by BY-G** [Bin-Huang/chatbox#1236]
**Bug Description**
When using the OpenAI API provider, "Current model: XXX" will be added in front of the system prompt.

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1227, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

**Comment by nullstreak** [comment]
>  It seems that you are using OpenAI's provider interface to access other services, which I think is a special case. Perhaps, instead of removing the prompt line, I should consider adding support for this particular service.

@Bin-Huang You can't account for all services that might use OpenAI's provider interface. It's pretty much universal thing now. But if you think it's a good idea, please implement support for [gpt4free](https://github.com/xtekky/gpt4free).

Anyway, I don't understand why you're trying to combat a single case of AI model hallucination by degrading performance for every user. Seems a bit excessive. Don't you think OpenAI should be working on this instead of you?

**Comment by rodion-m** [comment]
@Bin-Huang Hi! Thanks again for a great tool! I've donated recently. 

> I don't understand why you're trying to combat a single case of single AI model hallucination by degrading performance for every user with every model.

This question is really relevant. Could you please make this feature at least optional?

**Comment by Bin-Huang** [comment]
<img width="376" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/8b1717ff-516c-40ea-ab17-ff30409b576f">
I've added a small switch, which will be released in the next version
