### ISSUE TITLE
[BUG] Chatbox-1.3.3-arm64.dmg triggers JS/Agent.OBF false positive??

### ISSUE THREAD

**Issue by fleytman** [Bin-Huang/chatbox#1270]
**Bug Description**
ESET Endpoint security found 
> Chatbox-1.3.3-arm64.dmg » DMG » 4.hfs » HFS » app.asar » ASAR » dist\renderer\renderer.js - JS/Agent.OBF trojan

But the latest version Chatbox-1.3.1-arm64.dmg on github doesn't show any trojans.

P.S. I see that just before the 1.3.3 version the license was changed to MIT. It is very alarming that a version with a trojan appears right after that.

<img width="925" alt="Снимок экрана 2024-03-30 в 15 48 23" src="https://github.com/Bin-Huang/chatbox/assets/1923645/1b0c4bc7-8a29-4325-91f7-bfb32da1a650">
<img width="890" alt="Снимок экрана 2024-03-30 в 15 49 20" src="https://github.com/Bin-Huang/chatbox/assets/1923645/7be4329e-d112-445a-8aed-47453ba89ec8">

**Comment by MilanKovacic** [comment]
@Bin-Huang Can you comment on what exactly is going on?
Why is there a release that is not on GitHub?
Why was the license changed - such license change requires permission from all contributors whose code is still present?

**Comment by fleitman** [comment]
It's also bad that the github version offers to update with the version from the site, which has a trojan...

**Comment by fleytman** [comment]
It's also bad that the github version offers to update with the version from the site, which has a trojan...

**Comment by Bin-Huang** [comment]
I attach great importance to this issue and am currently investigating its source.

**Comment by Bin-Huang** [comment]
> @Bin-Huang Can you comment on what exactly is going on? Why is there a release that is not on GitHub? Why was the license changed - such license change requires permission from all contributors whose code is still present? Why are releases fetched from "https://pub-0f2a372de68244aabdee60c9d82c4c6c.r2.dev"? Website mentions the following changes for version 1.3.3:
> 
> > v1.3.3
> > You can now set user avatars in messages.
> > Added support for configuring a custom API host for Gemini.
> > Implemented an option in settings to enable or disable Markdown and LaTeX rendering.
> > Fixed issues with LaTeX rendering.
> > Fixed potential stuttering and crashing issues during message generation.
> > Fixed issues with redundant pop-up prompts during auto-updating.
> > Fixed various minor bugs.
> 
> None of these features/fixes seem to be in the current code at GitHub ([v1.3.1...main](https://github.com/Bin-Huang/chatbox/compare/v1.3.1...main)), so where are they?

I am investigating the cause of this issue. Before proceeding, I would like to clarify that the installation packages from the website distribution and Github releases are both from the same Github Actions pipeline. The reason I offer website distribution is purely because in some countries and regions (such as China), downloading from Github releases is extremely slow.

**Comment by Bin-Huang** [comment]
## No Security Issues Detected

I have **NOT** detected any security issues in all the system distributions of version v1.3.3 provided on the website.

From ESET:
![Apr-01-2024 10-25-42](https://github.com/Bin-Huang/chatbox/assets/20723142/21d1ca23-e7c6-45e6-bfc4-8df4a7e5d52e)

From Avira:
![Apr-01-2024 10-43-03](https://github.com/Bin-Huang/chatbox/assets/20723142/4188c768-c1aa-4c72-8d3f-52ac1eb00981)

Meanwhile, I have checked all potential areas that might have been overlooked. And I searched the Internet for JS/Agent.OBF and didn't find any fully relevant vulnerability disclosures. At present, I believe that the current distribution version of the website does not have any security issues.

@fleytman Could you send the file with the warning to [tohuangbin@gmail.com](mailto:tohuangbin@gmail.com)? That way, I can further determine where this file came from.

## Answer to the Appeal Question

#### Why is there a release that is not on GitHub?

I've been using Github Actions to build and distribute releases. After Github Actions finishes running, it automatically creates a draft in Github Releases, which requires manual editing and confirmation to be publicly displayed. Since I always release new versions late on Sunday nights (developing intensively on Saturdays and Sundays, starting intensive testing at noon on Sunday), each build takes about an hour, and I have missed many drafts that weren't made public...

<img width="700" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/0c966e7a-3102-40cf-bd3b-59580f019fe8">

In addition, after Github Actions finishes running, it also uploads new installers to my Cloudflare R2 storage, and the website automatically distributes the latest version. This greatly reduces my workload. I'm also using this site to improve the download speed of the installation package in various countries because there are serious network delays when accessing GitHub Releases in some countries. No one has mentioned there being any issue with this before.

#### Why was the license changed - such license change requires permission from all contributors whose code is still present?

Oops, it seems my changes were a bit casual, I apologize for my actions. The reason I modified the license is because I recently received an email from a developer who wants to fork this repository and develop new open-source project on top of it. This made me realize that the original license might hinder others' work (although this developer was willing to follow it), so I changed it to the more liberal MIT license to make it easier for other potential developers to work on their own projects. Most of the code was written by me, and initially, it was under the MIT license. I was unaware of the requirements for changing a license, and I apologize again for my actions.

<img width="1340" alt="Screenshot 2024-04-01 at 11 21 18" src="https://github.com/Bin-Huang/chatbox/assets/20723142/eec449f7-f57e-4dc7-b03c-1b4c42fa890d">

#### Why are releases fetched from "https://pub-0f2a372de68244aabdee60c9d82c4c6c.r2.dev/"?

As I mentioned above, this is my Cloudflare R2 storage bucket, which facilitates the release of new versions and allows people from various countries to download at faster speeds.


#### Finally

I've always kept an eye on security issues with vigilance and precaution during the development and maintenance phase, and my professional expertise and competence (as a senior software engineer) enable me to develop secure and reliable software. Emotionally, I've devoted a year of intensive work to this project, spending all my spare time here, and I'm the last person who would want anything to go wrong with it.

I have scanned the installation packages offered by the website and used different security software, but haven't found any problems. I believe the software is secure enough.

**Comment by MilanKovacic** [comment]
Glad to hear everything's in order, and my questions were aimed at understanding the situation for everyone's peace of mind. Thank you for addressing the concerns. Appreciate your quick response!

**Comment by fleytman** [comment]
@Bin-Huang Good afternoon, thanks for the reply. I checked the macOS version yesterday via virustotal but found nothing. Today I decided to check the vindos version and nod32 trojan is found: 
https://www.virustotal.com/gui/file/54dfe2fb22549587683210038010baa59d8da9dfc222bd62a1d6db35748d5b2d
At the same time, version 1.3.1 does not find https://www.virustotal.com/gui/file/7bc9d872729d2795fb509e913b955e6abd916f6a7f0d1ac34b40f7cfd9898034.

Maybe it's false detection, maybe not. Maybe you should contact eset for more details. For example on their forum https://forum.eset.com/.
I get my antivirus scan files from https://chatboxai.app . I originally discovered the problem when the antivirus reacted to an already installed application. Alas, I am not allowed to re-install the application because of the trojan detection.... But here is a screenshot from the report that the antivirus initially detected:

<details><summary>screenshot</summary>
<p>
<img width="1499" alt="Screenshot 2024-04-01 at 15 51 53" src="https://github.com/Bin-Huang/chatbox/assets/1923645/3e3f177c-2bbb-420b-8436-c96b0b10bc26">
</p>
</details> 


From what I've found on the topic
https://github.com/electron/electron/issues/1205
https://www.f-secure.com/v-descs/trojan-downloader-js-agent-fdl.shtml

Translated with www.DeepL.com/Translator (free version)

**Comment by fleytman** [comment]
@Bin-Huang, I understand your interest in transitioning the Chatbox project to an MIT license, which undoubtedly can facilitate the software's integration and use in commercial projects. However, I would like to address the importance of GPL3 for the current and future developer community of your project.

Switching to an MIT license may require consent from all contributors who have contributed under GPL3. This is not only a legal necessity but also a matter of respecting and valuing their contributions. Therefore, I recommend that you first reach out to each contributor to obtain permission for such a change.

Furthermore, have you considered dual licensing? This would allow for the spirit of open source, protected by GPL3, to be maintained while also offering a more flexible MIT approach for those interested in commercial use. Dual licensing would enable the community to continue developing forks of your project strictly within the GPL3 framework, which may be important for those who value the principles of open source and wish to see their contributions remain free and accessible to all.

This approach could serve as a compromise that satisfies both open-source advocates and those seeking easier paths to commercialization.

**Comment by Bin-Huang** [comment]
Thank you for your suggestions. I have reverted the changes made to the license, rolling it back to GPL. Moving forward, I will seriously consider a dual-license approach. Given that other contributors' code makes up a small part of the project, and much of it is outdated, the transition to a dual licensing model may go smoothly.

I want to return to the initial issue of security warnings that we discussed. I'll keep this GitHub issue open for a while to see if there is any follow-up or if anyone else encounters a similar situation. After that period (a few months), I might close this issue to streamline management.

In this age of rapid iteration of AI/LLM technologies, maintaining such an open-source project is indeed an urgent and hefty task. Thank you very much for your understanding.

**Comment by fleytman** [comment]
1.3.4 virus total without trojan https://www.virustotal.com/gui/file/70b1e78c8bb7cf00f17a7a2e6f3a984cb46e12bf81ee8dd19c573dec96d5ce81

Can i disable autoupdate?

**Comment by art-mis** [comment]
@Bin-Huang and could you please tell me how I could disable automatic updates of Chatbox to avoid similar problems in the future?

**Comment by WiSaGaN** [comment]
> > v1.3.3
> > You can now set user avatars in messages.
> > Added support for configuring a custom API host for Gemini.
> > Implemented an option in settings to enable or disable Markdown and LaTeX rendering.
> > Fixed issues with LaTeX rendering.
> > Fixed potential stuttering and crashing issues during message generation.
> > Fixed issues with redundant pop-up prompts during auto-updating.
> > Fixed various minor bugs.
> 
> None of these features/fixes seem to be in the current code at GitHub ([v1.3.1...main](https://github.com/Bin-Huang/chatbox/compare/v1.3.1...main)), so where are they?

@Bin-Huang I am also one of the happy user that is currently on 1.3.3, thus concerned about the situation. Thanks for all the explanation, it really helps clearing things up. However, I haven't found any explanation on why the code for 1.3.3 is not on Github. And if it is possible to push the 1.3.3 code in the github so others can reproduce the binary to check where the problem is?

**Comment by Bin-Huang** [comment]
Here is the v1.3.3 version that I supplemented in GitHub Actions (I just made it public with a click), hoping it will be useful to those in need.

https://github.com/Bin-Huang/chatbox/releases/tag/v1.3.3

**Comment by WiSaGaN** [comment]
Sorry, I may have misunderstood something. But this tag points to https://github.com/Bin-Huang/chatbox/commit/32f196ae062d0554dd6daa922cfad8420fd39498 , which is the change to revert the license back to GPL from MIT on April 2?

**Comment by MilanKovacic** [comment]
> Sorry, I may have misunderstood something. But this tag points to [32f196a](https://github.com/Bin-Huang/chatbox/commit/32f196ae062d0554dd6daa922cfad8420fd39498) , which is the change to revert the license back to GPL from MIT on April 2?

There is information regarding this in https://github.com/Bin-Huang/chatbox/issues/803#issuecomment-1797994508.
Essentially, the product has become closed source from my understanding.
This is very confusing for consumers, as most people would expect GitHub releases being published from the repository.

**Comment by Bin-Huang** [comment]
Sorry for the mistake in closing the issue.

**Comment by Bin-Huang** [comment]
Here I attach the message discussed on Twitter.

<img width="462" alt="截屏2024-04-16 21 27 23" src="https://github.com/Bin-Huang/chatbox/assets/20723142/eecb1220-17e2-43fc-9f41-a436e7cd0ce3">

https://github.com/electron-userland/electron-builder/issues/6474

**Comment by fleytman** [comment]
>Add a certificate signature to the software (I've spent a decent amount of money to purchase a certificate from DigiCert).

I recommend making a separate announcement that you had to spend money on the certificate, stating how much it cost and a link for donations

**Comment by Bin-Huang** [comment]
Just like we discussed before, it's more likely a false positive from all aspects now. To better manage the issues, I've closed it for now.

**Comment by Bin-Huang** [comment]
I've checked all the dependencies and found some that need updating. Don't worry - these outdated dependencies don't affect user data security, they just cause some app slowdown and unresponsiveness when inputting data (like this issue: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw). I've already updated all the necessary dependencies, and these changes will be included in the next release.

帮我写一条英文评论，表达这个意思：我检查了一下所有的依赖项，确实有一些值得升级。不过这些过时的依赖并不会影响用户的数据安全，只是会导致某些输入时应用卡顿与不可用（例如这个 https://github.com/advisories/GHSA-c2qf-rxjj-qqgw ）。我已经全面升级了所有需要升级的依赖项，这个更新将会在下一个版本中发布。

**Comment by CallMeR** [comment]
> 因此，我已经决定在下一个版本中，适当降低代码的混淆等级，以此来规避误报问题。

1.7.1 在火绒检测下，还是有 downloader 病毒的问题。

**Comment by Bin-Huang** [comment]
I think I understand what's causing this now. I'm using [electron-updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater) for the auto-update feature in Chatbox software. It's actually a super popular update library in the Electron community. I've noticed from their GitHub issues that some antivirus software might flag it as suspicious on certain systems. There are quite a few discussions about this in the community, but unfortunately, there doesn't seem to be a good way to avoid these **false positives** at the moment.

我大概明白是什么原因了。我正在使用 electron-updater 这个工具库来实现软件自动获取更新。这是一个在 electron 社区中非常热门和流行的自动更新工具库。我曾经在它的 issues 中观察到，它的行为方式可能在某些系统中容易被误报成安全问题。目前在社区中存在很多这样的讨论，但是目前看似乎没有办法来规避**误报**。
