### ISSUE TITLE
[SECURITY] Why is chatbox requesting system events permissions on MacOS. This is highly suspicious.

### ISSUE THREAD

**Issue by cocoonkid** [Bin-Huang/chatbox#1561]
https://old.reddit.com/r/ChatGPT/comments/1fxrddl/chatbox_app_macos_custom_client_requesting/

This is HIGHLY SUSPICIOUS! 

Can be disabled here:

![image](https://github.com/user-attachments/assets/2a4383f6-882e-4894-92dc-322bd5166c60)

**Comment by Bin-Huang** [comment]
Don't worry too much. The new 1.5.0 update just added an option to enable auto-launch on startup. It's disabled by default, but you can turn it on in the settings if you want. Technically, this requires that permission because the Chatbox app uses a certain npm library (https://www.npmjs.com/package/auto-launch) that needs that access. But it's nothing too concerning; it's just a standard feature addition.

**Comment by Bin-Huang** [comment]
Adding more details: auto-launch is a super common package for setting up apps to start automatically on boot. The package's README mentions that it needs System Events permissions to work its magic. https://github.com/Teamwork/node-auto-launch?tab=readme-ov-file#applescript-default

**Comment by Bin-Huang** [comment]
Just recompiled and re-released Chatbox v1.5.0. Fixed a bug on MacOS where it'd ask for System Events permission access right at the application startup, which should only happen when enabling auto-launch (default disabed, you can turn this on in settings). I decided to reuse this version number to avoid bugging users who've already updated with too frequent releases. https://x.com/benn_huang/status/1843896074026791246

**Comment by cocoonkid** [comment]
@Bin-Huang 

Thank you for the mitigation and explanation! 

Highly appreciated!
