### ISSUE TITLE
Chatbox 创建完用不了为什么 在国外不让用吗？

### ISSUE THREAD

**Issue by kimi7067** [Bin-Huang/chatbox#1670]
遇到了来自 Custom Provider 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 404, {"error":{"code":404,"message":"The requested resource was not found. Please check the URL and try again. Documentation is available at https://docs.x.ai/"}}

**Comment by kimi7067** [comment]
![屏幕截图 2024-12-08 103122](https://github.com/user-attachments/assets/921df9a2-7d29-4e62-91b9-4270ef468e53)

**Comment by Bin-Huang** [comment]
很明显是配置不正确，你试着给 API 域名后面加上 /v1 试一下

**Comment by kimi7067** [comment]
好的谢谢

Benn Huang ***@***.***>于2024年12月8日 周日17:46写道：

**Comment by Vic1946** [comment]
解决了吗？ 是不是好像不行？

**Comment by Bin-Huang** [comment]
xAI 可以完全正常地在 Chatbox 中集成使用。如果遇到了错误，要么是设置问题，要么是账户问题。

### xAI 设置

1. 创建自定义模型提供方
2. API Host: `https://api.x.ai/v1`
3. API Path：`/chat/completions`
4. Model：`grok-beta`
5. 设置正确的 API Key

只要保证上方配置正确，在海外网络下一定可以正常访问到 xAI。

### xAI 账户问题

如果配置正确、网络正常的情况下，之前用得好好的，突然某天就不能用了，那么一定是遇到了 xAI 本身账户问题（与 Chatbox 无关）。

据我个人观察主要有几种情况：

1. 账户网络被封。如果错误中包含了 `Blocked due to abusive traffic patterns` 等信息，那么说明 xAI 账户因为网络访问历史记录被封禁了（比如之前在不支持的国家访问了 xAI 的 API）。
2. 账户配额问题。我观察到 xAI 似乎也有配额限制，在重度使用后可能出现包含 `Some resource has been exhausted`、`has either used all available credits or reached its monthly spending limit. To continue making API requests, please purchase more credits or raise your spending limit`。这些错误信息都是在提醒你的 xAI 账户已经用完可用余额，需要给 xAI 充值。

**Comment by kimi7067** [comment]
解决了，谢谢大佬

Vic1946 ***@***.***>于2025年1月2日 周四12:07写道：

**Comment by 1781005133** [comment]
![Image](https://github.com/user-attachments/assets/313b2e4c-9b0a-440b-8128-96f5ff99a598)
我也遇到了类似的问题，我使用的是硅基流动上的deepseek模型。我试了你的办法，好像还是无法解决
