### ISSUE TITLE
I want running chatbox 2

### ISSUE THREAD

**Issue by cheeco-feng** [Bin-Huang/chatbox#573]
I want to implement the program of additional features:
I want running  "chatbox"x2, concurrently use gpt3.5 and gpt4.0 apikey used by the configuration.
After all, their cost is not the same.
Would you like to?

**Comment by Bin-Huang** [comment]
I had a similar plan a while ago. I think it's important to differentiate between the global default settings for models and the individual session settings, so that each session can have its own model selection, allowing for the use of both GPT 3.5 and GPT 4. In addition to the model version, individual sessions can also implement their own temperature control, which is great for distinguishing between creative and rigorous sessions. Of course, this change requires a certain amount of work, such as implementing the functionality, creating a UI for session settings, and providing tips to help users understand the difference. I plan to consider implementing this feature in two weeks. If you're interested, you can try to implement it now, and I'd be very grateful for the contribution. We can discuss this further.

**Comment by Bin-Huang** [comment]
The discussion above has already been implemented in previous version updates, try updating and see.
