### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by klj123wan** [Bin-Huang/chatbox#637]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。
{"error":{"message":"This model's maximum context length is 4097 tokens. However, you requested 4229 tokens (2181 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}

**Comment by mirkoschubert** [comment]
I have the same error message in one of the chats. I'm on `macOS 13.4` and `ChatBox 0.4.5` with the `gpt-3.5-turbo` model. I have the defaults in the settings, max_tokens is at 4000.

When I understand it correctly, the model saves previous requests and responses in a completion, but it's limited to 4097 tokens for now. So the next request must be truncated. But I don't know the API, so I don't know if you send the context of previous messages or how to handle this programmatically.

**Comment by Bin-Huang** [comment]
The actual reason is very simple. ChatGPT and the API are two different account systems of OpenAI. Your API account has no balance or the balance has expired, so you need to bind an overseas credit card to the account to continue using it. This issue has nothing to do with the software.
If you don't want to bother with various issues related to the API account, it is strongly recommended to use the built-in AI service added in Chatbox v0.5.0, which is ready to use and doesn't require any network or account issues. https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
