### ISSUE TITLE
[Question] Why isn't the source code for Azure OpenAI support included in this repository?

### ISSUE THREAD

**Issue by zthxxx** [Bin-Huang/chatbox#694]
I discovered that the Azure API support in v0.4.4 was not fully compatible with the official Azure API. I wanted to check the details to fix it, however, I couldn't find them in the source code. 

I searched through both the `main` branch, the `v0.4.4` tag, and the source code zip file on the release page with `v.0.4.4` version.

This also raises concerns about the security of my API key. Could it potentially be leaked to any server?

**Comment by Bin-Huang** [comment]
The API Key will not be leaked to any server. It's not something I would do. I have temporarily hidden some of the recently updated source code because I found that many training institutions are not complying with the open source agreement and are directly selling my code, which is causing me a lot of distress.
