### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by lssgit** [Bin-Huang/chatbox#708]
建议在设置中增加一个选项，能够查询到 当前 key 的使用情况，如余额 、已使用、剩余额度等信息，如果作者想适度商业化的话，对国内用户提供一些 Key 充值服务，代收取一些手续费是不错的选项。（国内充值 openAi 实在太不方便了）

**Comment by Bin-Huang** [comment]
Thank you for your contributions. It seems that this issue has been inactive for a while and may no longer be relevant due to evolving project requirements. To help keep the project organized and maintainable, I’ll be closing this issue for now.

If you believe that the issue is still relevant and requires further discussion or you have any new information to provide, please feel free to reopen it or create a new issue with updated details.

Thanks again for your understanding, and your efforts toward improving the project are greatly appreciated!
