### ISSUE TITLE
错误如何处理？{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

### ISSUE THREAD

**Issue by STU-Z** [Bin-Huang/chatbox#745]
在使用ChatBox过程中，出现了以下报错：
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
而实际上，我检查了账户上的余额，并且重置了Key，API请求仍然失败。

**Comment by QzCrane** [comment]
same

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，可以考虑 Chatbox 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases

In fact, the reason is already in the error message. API accounts and ChatGPT accounts are two separate systems by OpenAI. Your API account may have run out of balance or the balance has expired. To continue using it, you need to link an overseas credit card to your account. This issue is not related to the software.

If you don't want to deal with various API account issues, consider using the built-in AI service recently added to Chatbox. It's plug-and-play, so you won't need to worry about network or account problems anymore. https://github.com/Bin-Huang/chatbox/releases

**Comment by bobozy1999** [comment]
> 其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。 这个问题和软件没有任何关系。 如果你不想折腾 API 账户的各种问题的话，可以考虑 Chatbox 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases
> 
> In fact, the reason is already in the error message. API accounts and ChatGPT accounts are two separate systems by OpenAI. Your API account may have run out of balance or the balance has expired. To continue using it, you need to link an overseas credit card to your account. This issue is not related to the software.
> 
> If you don't want to deal with various API account issues, consider using the built-in AI service recently added to Chatbox. It's plug-and-play, so you won't need to worry about network or account problems anymore. https://github.com/Bin-Huang/chatbox/releases

怎样调用 Chatbox 新增的内置 AI 服务呢，需要另外付费吗

**Comment by Bin-Huang** [comment]
升级到最新版本，在设置中可以看到。
AI 服务的成本很高，没能力做到完全免费，如果使用内置 AI 服务的话需要支付成本费用（具体成本公式在支付详情）。
