### ISSUE TITLE
[Other] Source code update

### ISSUE THREAD

**Issue by gmq** [Bin-Huang/chatbox#803]
Any chance of updating the repository code to reflect the latest compiled version? The code seems to have been mostly left behind after 0.4.4, with none of the new features.

**Comment by thuongtin** [comment]
I am also interested in this. I want to build a separate version to use GPT-4.

**Comment by evanre** [comment]
@Bin-Huang Is there any official response regarding this matter? What is the purpose of this repository? Without an updated source code, I perceive this application as proprietary, leaving room for any undisclosed aspects.

**Comment by Bin-Huang** [comment]
😄 I believe I've responded to similar discussions on other issues before, and I can reiterate my thoughts here: I've spent months laboring under high pressure within Chatbox, sacrificing my life and sleep, yet I still feel it is worthwhile to contribute to the open-source community. I'm not the type of person who requests reciprocation; many of my side projects, including Chatbox, are entirely free and done without expecting anything in return. All of Chatbox's features are completely free. However, I've encountered significant emotional distress in maintaining Chatbox, which led me to decide not to immediately release all update source codes: I found that Chatbox has attracted many people who do not abide by the open-source agreement. They steal the source code and pursue their grey-area businesses. These people only want to profit quickly and allow the Chatbox interface and logo to appear on paid access, uncredited, and easily shut-down websites. In the end, I noticed they took the money while leaving all development, maintenance, and customer service explanations to me......

This will not deter my enthusiasm for development, but it means I cannot immediately release all updated source codes anymore. That period was the worst I've ever felt, and this is a hard decision to make 😢. At the same time, as a client app, much of Chatbox’s work is tedious and non-technical, such as adjusting the UI for one or two pixels, testing on different devices, and displaying effects... I also noticed that open-source isn't always the best development method, many contributions fulfill functionalities at the technical level but are far from excellent, and the communication cost based on UI and product design is high.

So please forgive me for not being able to continue updating the source code immediately, as this is the only way to keep Chatbox developing (as opposed to ceasing maintenance in disappointment). I believe what people need more is a handy, free, continually updated software, rather than a fully open-source and difficult-to-maintain program. Although I will gradually open-source update the codes in the future, until then, let Chatbox be completely free and partially open-source software! 😊🚀 In fact, this is also one of the development models of many open-source software.

**Comment by bnbp** [comment]
@Bin-Huang Respect your decision, but since you chose the GPLv3 license, please stop publishing closed source binaries in this repository, it will make people confused.

**Comment by tangdou1** [comment]
Oh, No. In fact, the chatbox has become a free closed source software since the version(> 0.4.4). Right?

**Comment by CoREse** [comment]
> 😄 I believe I've responded to similar discussions on other issues before, and I can reiterate my thoughts here: I've spent months laboring under high pressure within Chatbox, sacrificing my life and sleep, yet I still feel it is worthwhile to contribute to the open-source community. I'm not the type of person who requests reciprocation; many of my side projects, including Chatbox, are entirely free and done without expecting anything in return. All of Chatbox's features are completely free. However, I've encountered significant emotional distress in maintaining Chatbox, which led me to decide not to immediately release all update source codes: I found that Chatbox has attracted many people who do not abide by the open-source agreement. They steal the source code and pursue their grey-area businesses. These people only want to profit quickly and allow the Chatbox interface and logo to appear on paid access, uncredited, and easily shut-down websites. In the end, I noticed they took the money while leaving all development, maintenance, and customer service explanations to me......
> 
> This will not deter my enthusiasm for development, but it means I cannot immediately release all updated source codes anymore. That period was the worst I've ever felt, and this is a hard decision to make 😢. At the same time, as a client app, much of Chatbox’s work is tedious and non-technical, such as adjusting the UI for one or two pixels, testing on different devices, and displaying effects... I also noticed that open-source isn't always the best development method, many contributions fulfill functionalities at the technical level but are far from excellent, and the communication cost based on UI and product design is high.
> 
> So please forgive me for not being able to continue updating the source code immediately, as this is the only way to keep Chatbox developing (as opposed to ceasing maintenance in disappointment). I believe what people need more is a handy, free, continually updated software, rather than a fully open-source and difficult-to-maintain program. Although I will gradually open-source update the codes in the future, until then, let Chatbox be completely free and partially open-source software! 😊🚀 In fact, this is also one of the development models of many open-source software.

Remove the "open-source" propaganda then, and stop pretending you are providing an open-source build of executables in the release and mark that the executables are not open-source, if you truly want people to understand you. Frankly speaking, your behavior can be considered fraudulent, not better than those people you claimed to be "who do not abide by the open-source agreement". Currently you enjoy the benefits of open-source projects and the freedom to keep your source closed, and you still want others to understand you? Remove the "open-source" mark and stop building a false appearance of an active open-source project by making insignificant updates now and then, and there will be no blame, except for the loss of users, but those users who care about whether the software they use is open-source do not deserve to be conned.

**Comment by realiti4** [comment]
Like others have mentioned, I respect your decision but this model is highly confusing. I realized a little bit too late that I am using a closed sourced software, and this codebase really really old. Main channel's dependencies is also messed up, not even working at the current state. I spent a little bit of time trying to debug, then realized this codebase was not I was using on my computer, so decided not to.

**Comment by Bin-Huang** [comment]
I've been prepping a major code update for the past few weeks, please hang tight for a bit longer.

**Comment by Bin-Huang** [comment]
This is a source code update I've prepared, which includes countless refactoring and optimization efforts I've made over the past year. Essentially, it's a complete rewrite.

https://github.com/Bin-Huang/chatbox/pull/1428

In essence, this is an entirely new codebase compared to the previous version. I've decided to keep it open-source as a contribution to the community.

To avoid any confusion, I want to clarify that this version doesn't include many new features that have been released. The main goal of this PR is to update the core of the application, fix existing issues, and improve basic user experience and performance, paving the way for future updates and iterations. This repository might become the community version of Chatbox, distinct from the official Chatbox release.

**Comment by jpike88** [comment]
@Bin-Huang Eyeballing and testing your latest update I'm glad you're doing a great service for the community. You haven't pushed your business on people, just decided to focus on something that provided for you.

People should bear in mind that open source is in practice little more than a social contract; there's nothing stopping a maintainer from just taking his ball and going home, leaving a project in the lurch. Anyone who's running an open source project out of the goodness of their heart either has an incredible amount of free time (and money to back it up), or wants to get some kind of commercial outcome out of it. For those who are employees and not businesspeople, you will never understand.

So I appreciate you updating the source code, but I respect your hustle, and ask that you remember to take care of yourself first. None of the people in this thread will do it.

**Comment by fleytman** [comment]
At the moment, the latest open source version is automatically updated to the closed source version from the site. This also leads to potential security issues, especially when used in a corporate environment. Please disable auto-update to the version from the site for the version from this repository. If you want to transfer people to the version from the site, it is more correct to suggest updating to the closed version in the app interface, explaining the advantages and leaving the user to choose.

**Comment by Bin-Huang** [comment]
I totally agree with @andsofine 's point. I've added a clear statement at the top of the README, and I think this addition will address the issue. I’m closing this issue because the discussion has become too broad and it's been open for a while. If there are any specific concerns or new points, feel free to open a new issue.

**Comment by Bin-Huang** [comment]
I've removed all potentially misleading tags and releases. I hope Chatbox can keep evolving with a distinction between community and official versions. Keep moving forward!

**Comment by fleytman** [comment]
Thank you for making this clear. I see that there are no hotkeys and no import / export in the community version. Is this intentional or just lost? It's especially strange if you can't transfer data from the community version to the full version. This may demotivate you to switch to it.
