### ISSUE TITLE
[BUG] Releases still use Electron (where is tauri?)

### ISSUE THREAD

**Issue by Tokarak** [Bin-Huang/chatbox#840]
Looking at the latest release [v0.6.2](https://github.com/Bin-Huang/chatbox/releases/tag/v0.6.2), all binaries are ~100MB compressed in size - this can only be because they use the electron framework. Tauri builds should be ~10MB.

The latest release with tauri builds is [v0.5.6](https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.6). I tested building-from-source using Tauri successfully, on an M1 Mac.

I see no reason to provide electron binaries, nor any previous discussion about this.

---
（谷歌翻译）

查看最新版本 [v0.6.2](https://github.com/Bin-Huang/chatbox/releases/tag/v0.6.2)，所有二进制文件的压缩大小约为 100MB - 这只能是因为它们使用电子框架。 Tauri 构建应该约为 10MB。

tauri 版本的最新版本是 [v0.5.6](https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.6)。我在 M1 Mac 上成功地使用 Tauri 测试了从源代码构建。

我认为没有理由提供电子二进制文件，也没有任何先前的讨论。

**Comment by Bin-Huang** [comment]
I think this indicates my oversight in managing GitHub Issues, as issues related to tauri have been a persistent problem for the chatbox project. The development experience with tauri has been smooth for developers, but it has introduced compatibility issues for end users. Many issues have been reported, such as blank screens after updates, installation problems on Windows, crashes after Windows upgrades, and slow performance on Ubuntu. These issues are scattered across different bug reports, all related to tauri.

Technically, these issues are unavoidable for tauri-based applications. Tauri uses the system's native webview as its rendering layer, which inherently leads to platform differences. Additionally, different systems may have varying levels of focus and maintenance on their webviews, often resulting in webview damage. For example, a recent Windows system update damaged the built-in webview2, rendering chatbox unusable for all users on that system version.

I feel exhausted dealing with these problems because many of them are inherent to the tauri framework, with no foreseeable plans for fixes in the tauri framework project. Therefore, from a technical standpoint, it is necessary for chatbox to migrate to a more mature and stable development framework, and currently, electron seems to be the most viable option.

**Comment by Tokarak** [comment]
Thanks for the reply. It's good to know at least that most people could compile with Tauri, if they wanted too.

**Comment by wwwang-bo** [comment]
@Bin-Huang Now Tauri has been upgraded to version 2.0. Will the issues you mentioned still be present in the latest version? Do you have any plans to use Tauri?
