### ISSUE TITLE
[Other]

### ISSUE THREAD

**Issue by Alan-88** [Bin-Huang/chatbox#896]
有没有办法添加LaTex之类的公式支持，让app能够渲染出gpt这种形式的输出，这样可以更直观地看到其输出的数学公式

**Comment by Bin-Huang** [comment]
其实已经支持了的，试着让 AI 用 KaTex 的方式回答你![image](https://github.com/Bin-Huang/chatbox/assets/20723142/2e644731-5cc6-42d7-a6ea-57cbc335309d)

**Comment by Alan-88** [comment]
不，还是没有效果，同样的问题，他给我的是“E = mc^2”，我用的是MacOS，是缺了什么吗

**Comment by M-10777** [comment]
并不是：
若模型使用`\(`和`\)`，`\[`和`\]`作为公式起始/结束标识符，那么它们确实无法被正确识别。
我尝试发现可以用`$`和`$$`代替
可以在Prompt中添加相应提示，如：
`行内公式应以$作为开始/结束标记而不是\(和\)；行间公式应该使用$$而不是\[和\]`
或
`Intra-line formulas should use $ as a start/end marker instead of \( and \); inter-line formulas should use $$ instead of \[ and \]`

模型：GPT-4-1106-Preview
